# Secret containing the kubeconfig for the seed cluster that shall be registered.
---
apiVersion: v1
kind: Secret
metadata:
  name: seed-secret
  namespace: garden
type: Opaque
data:
  kubeconfig: <seed-cluster-kubconfig-base64>
  # cat dev/kops-gardendev.yaml | base64 -w 0