# Secret containing provider-specific credentials for account that shall be used to deploy the shoot into.
---
apiVersion: v1
kind: Secret
metadata:
  name: my-provider-account
  namespace: garden-dev
type: Opaque
data:
  accessKeyID: <key-id-base64>
  secretAccessKey: <key-base64>