global:
  # Gardenlet configuration values
  gardenlet:
    config:
      gardenClientConnection:
        bootstrapKubeconfig: # bootstrapKubeconfig contains the kubeconfig that is used to initiate the bootstrap process, i.e.,
                               # that is used to request a client certificate for the garden cluster. The name and namespace fields
                               # are a reference to a secret that will store this bootstrap kubeconfig. If `kubeconfig` is given
                               # then only this kubeconfig will be considered.
          name: gardenlet-kubeconfig-bootstrap
          namespace: garden
          kubeconfig: |
            apiVersion: v1
            clusters:
            <gardenlet-kubeconfig>
        kubeconfigSecret: # kubeconfigSecret is the reference to a secret object that stores the gardenlet's kubeconfig that
                            # is used to communicate with the garden cluster. This kubeconfig is derived out of the bootstrap
                            # process. If `kubeconfig` is given then only this kubeconfig will be considered.
          name: gardenlet-kubeconfig
          namespace: garden
      seedSelector:
        test: foo
      deployment:
        virtualGarden:
          enabled: false
